/**
 * Shared types for the four screen archetypes (blueprint §5.1). Each legacy
 * form maps onto one of these; a route file resolves a FormSpec and hands it
 * to the matching template component, rather than every screen being
 * hand-built bespoke React.
 */

export type FieldType =
  | "Data"
  | "Text"
  | "Small Text"
  | "Int"
  | "Float"
  | "Currency"
  | "Date"
  | "Datetime"
  | "Time"
  | "Check"
  | "Link"
  | "Select"
  | "Attach"
  | "Attach Image"
  | "Signature"
  | "Table"
  | "Autocomplete"
  | "Section Break"
  | "Column Break"

export interface FieldSpec {
  fieldname: string
  label: string
  fieldtype: FieldType
  options?: string
  required?: boolean
  readOnly?: boolean
  inListView?: boolean
  section?: string
  dropdown?: boolean
  dependsOn?: string
  /** Declarative only — not yet evaluated by any renderer (FinanceDynamicField only reads the static `readOnly` flag). */
  readOnlyDependsOn?: string
  description?: string
  linkStaticFilters?: Record<string, unknown>
  linkFilterFields?: string[]
  /** For a Link dropdown: additional fields to fetch from the target doctype and join into the option's display label, instead of showing the raw `name` — needed when `name` is an autogenerated hash rather than something human-readable (e.g. SMS Student, which has no autoname pattern). */
  linkLabelFields?: string[]
  /** Link field renders as a type-to-search combobox (fetches matching records live) instead of a plain text input. Only meaningful when fieldtype is "Link". */
  searchable?: boolean
  /** Fields on the target doctype to match the typed query against (OR'd, LIKE %query%). Defaults to ["name"] when searchable is true and this is omitted. */
  searchFields?: string[]
  /** When set on a searchable Link field: after a record is picked, copy data from it (and optionally its newest related record) into other fields on this same form. Values are copied as-is -- a Link-type source field's stored value is the target doc's name, e.g. Program Enrollment.academic_year already IS the Academic Year's display name. */
  autofill?: {
    fields?: Record<string, string>
    relatedRecord?: {
      doctype: string
      linkField: string
      orderBy: string
      fields: Record<string, string>
    }
  }
}

export interface FormSpec {
  /** Legacy form name, kept for traceability back to the blueprint/VB source. */
  legacyForm?: string
  doctype: string
  title: string
  fields: FieldSpec[]
  /** Whitelisted campus_erp.api.* method backing this screen's primary action, if any. */
  primaryApi?: string
  /** Base route for a bespoke per-row detail page, e.g. "/registrar/students". When set, MasterDetailScreen renders a per-row link to `${detailPath}/${row.name}` alongside the existing edit-dialog row click. */
  detailPath?: string
  /** Base route for a bespoke "create new" page, e.g. "/registrar/students/new". When set, MasterDetailScreen's "Add {title}" button navigates there instead of opening the built-in dialog. */
  addPath?: string
  /** A status-like Select field plus the value representing a soft-retirement state (e.g. Student's sms_status="Dropped"). When set, MasterDetailScreen's row action menu gets a quick "Drop" item that patches just this field, instead of requiring the full edit dialog. */
  statusField?: { fieldname: string; droppedValue: string; label?: string }
  /** Doctypes that are safe to auto-delete, on request, when they're the reason a delete fails with Frappe's LinkExistsError — e.g. a Student blocked by its SMS Graduation Batch, a derived/computed artifact from the graduation run rather than source-of-truth data. When a delete fails because of one of these, MasterDetailScreen offers to delete the blocker and retry instead of just showing the error. Financial/ledger doctypes (Payment Ledger Entry, GL Entry) are listed here for Student specifically, and only because this project's actual data at the time was confirmed-disposable test/dev seed data with no real transactions behind it — that confirmation doesn't generalize to other doctypes or datasets. Adding a new financial/ledger doctype to any spec's list is exactly the kind of change that needs the same explicit, deliberate confirmation, not a default. */
  cascadeDeleteDoctypes?: string[]
  /** Submittable doctypes that must be cancelled (docstatus 1 -> 2) before they can be deleted — e.g. a Student blocked by a submitted SMS Student Assessment with posted GL Entries. Handled separately from cascadeDeleteDoctypes because cancelling reverses real financial/ledger entries: MasterDetailScreen shows a distinctly stronger warning naming that consequence before cancelling and deleting the blocker. Only list doctypes where cancel-then-delete is an intentionally sanctioned cleanup path, not routine cleanup. */
  cancelAndDeleteDoctypes?: string[]
  /**
   * Fields that logically belong on this record but actually live on a
   * separate linked doctype — e.g. a Student's current Program (course) and
   * Year Level, which live on their Program Enrollment, not Student itself
   * (a student can shift programs, so it's a separate history record, not a
   * Student field). MasterDetailScreen looks up the newest matching record
   * for the row being edited (by `linkField`), shows these fields in their
   * own labeled section, and patches that record on save — separately from
   * the base doctype update.
   *
   * By default it never creates a new related record (those typically need
   * other required fields this dialog doesn't collect), so the fields are
   * disabled with an explanatory note when no related record exists yet. Set
   * `allowCreate` to opt into the other behavior: `fields` become editable
   * even with nothing to edit yet, `additionalCreateFields` collects
   * whatever else creating one requires (e.g. Program Enrollment's required
   * `academic_year`, which isn't otherwise surfaced), and saving creates the
   * related record instead of patching one — but only once a real value
   * lands in `fields` (e.g. a Program is actually picked), so leaving
   * everything blank stays a no-op rather than creating an empty record.
   */
  relatedRecord?: {
    doctype: string
    /** Field on the related doctype linking back to this row's `name`. */
    linkField: string
    /** Field used to pick the most relevant record when several match (newest first). */
    orderBy: string
    /** Section label these fields render under in the edit dialog. */
    section: string
    /** Shown under the section heading when no related record exists yet. */
    missingRecordHint: string
    fields: FieldSpec[]
    /** Opt-in: create a new related record (instead of just disabling `fields`) when none exists yet. Default false leaves every other relatedRecord consumer unchanged. */
    allowCreate?: boolean
    /** Only used when `allowCreate` is true and there's nothing to edit yet -- fields the create call needs beyond `fields` and `linkField` (e.g. Program Enrollment's required `academic_year`). Never shown once a related record exists. */
    additionalCreateFields?: FieldSpec[]
  }
  /**
   * Small navigation shortcuts to a related record's own screen in another
   * module, shown once an existing record is loaded for editing (e.g. a
   * Student's edit dialog linking over to their Finance > Student Account
   * screen, and vice versa) — rendered generically by MasterDetailScreen
   * and FinanceEntryScreen, both of which already have the full row/doc in
   * hand at that point. `hrefFor` returns null to hide the link (e.g. a
   * related Link field that's empty), not to break navigation.
   */
  quickLinks?: Array<{
    label: string
    hrefFor: (row: Record<string, unknown>) => string | null
  }>
}

export interface ChildTableSpec {
  fieldname: string
  doctype: string
  /** Section/table heading — used when a child table is the entire body of a wizard step (e.g. "Leave Records", "Loans"), rather than a sibling of other fields. */
  title?: string
  /** Rendering variant for the grid — e.g. "gl-entries" for a debit/credit ledger-style table with running totals. */
  variant?: string
  columns: FieldSpec[]
}

export interface EntrySpec extends FormSpec {
  childTable?: ChildTableSpec
  /** Doctype is submittable (docstatus workflow) per blueprint §5.1. */
  submittable?: boolean
  /** Workflow actions available at the current state, e.g. ["Submit for Recommendation"]. */
  workflowActions?: string[]
  /** When set, EntryScreen renders this doctype's fields as a multi-step
   * wizard (WizardFormLayout) instead of one flat field grid. Optional and
   * opt-in — every other EntryScreen consumer is unaffected. */
  wizard?: WizardLayout
}

export interface ReportSpec {
  legacyForm?: string
  /** Either a registered Frappe Report name, or a raw whitelisted method. */
  report?: string
  method?: string
  title: string
  filters: FieldSpec[]
  columns: Array<{ fieldname: string; label: string; width?: number; fieldtype?: FieldType }>
  /**
   * Optional footer totals row - legacy screens like "Summary of Assessment"
   * have a bottom panel of running totals (e.g. Assessment/Dues, Collection,
   * Receivables) separate from the per-row grid. When set, the backing
   * `method` must return `{ rows, totals }` instead of a bare row array —
   * `totals` is a flat object keyed by each entry's `fieldname` here.
   * Reports without this property keep returning a bare row array,
   * unchanged (see ReportScreen for the backward-compatible handling).
   */
  totals?: Array<{ fieldname: string; label: string; fieldtype?: FieldType }>
}

export interface WizardStepSection {
  title?: string
  fieldnames: string[]
  columns?: 1 | 2 | 3 | 4
}

export interface WizardStepColumn {
  /** "main" renders wide (left), "sidebar" renders narrow (right). */
  span: "main" | "sidebar"
  sections: WizardStepSection[]
}

export interface WizardStepDialog {
  buttonLabel: string
  title: string
  /** Subset of the parent spec's own fields, shown flat inside the dialog. Mutually exclusive with childTable. */
  fieldnames?: string[]
  /** A full child-table grid inside the dialog instead of flat fields. Mutually exclusive with fieldnames. */
  childTable?: ChildTableSpec
}

/**
 * Step body precedence (WizardFormLayout.tsx must follow this order):
 *   1. columns    — two-region layout; when set, sections/fieldnames on the
 *                   step itself are ignored (put them inside columns[].sections instead)
 *   2. sections   — section-grouped flat fields
 *   3. fieldnames — plain flat field grid, no section grouping
 *   4. childTable — rendered IN ADDITION to whichever of the above is present;
 *                   a step can have fields AND a child table, or just a child table
 *   `dialog` is independent of all of the above — it renders as a trigger
 *   button at the end of the step regardless of which body variant is used,
 *   and does not by itself satisfy the "not built yet" check below.
 * A step with none of columns / sections / fieldnames.length / childTable
 * renders the "not built yet" placeholder, even if `dialog` is set.
 */
export interface WizardStep {
  key: string
  label: string
  /** Flat field list — used when the step doesn't need section grouping. */
  fieldnames: string[]
  fieldColumns?: 1 | 2 | 3 | 4
  /** Section-grouped layout — takes priority over `fieldnames` when present. */
  sections?: WizardStepSection[]
  /** Two-region (main/sidebar) layout — takes priority over `sections` and `fieldnames` when present. */
  columns?: WizardStepColumn[]
  /** A child table rendered alongside (or as the entirety of) the step's body. */
  childTable?: ChildTableSpec
  /** A button that opens a small dialog scoped to this step (e.g. "Policy", "View Infractions"). */
  dialog?: WizardStepDialog
  /** Shown instead of fields when a step has nothing built yet. */
  note?: string
}

export interface WizardLayout {
  steps: WizardStep[]
}